[versions]
agp = "8.3.2"
appcompat = "1.7.0"
constraintlayout = "2.1.4"
javaxServletApi = "3.1.0"
okhttp = "4.12.0"
recyclerview = "1.3.2"
localbroadcastmanager = "1.1.0"
documentfile = "1.0.1"
material = "1.12.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
javax-servlet-api = { module = "javax.servlet:javax.servlet-api", version.ref = "javaxServletApi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
localbroadcastmanager = { group = "androidx.localbroadcastmanager", name = "localbroadcastmanager", version.ref = "localbroadcastmanager"}
documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
material   = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

