[versions]
agp = "8.3.2"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
recyclerview = "1.3.2"
localbroadcastmanager = "1.1.0"
documentfile = "1.0.1"
[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
localbroadcastmanager = { group = "androidx.localbroadcastmanager", name = "localbroadcastmanager", version.ref = "localbroadcastmanager"}
documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

