[versions]
agp = "8.3.2"
appcompat = "1.6.0"
constraintlayout = "2.1.4"
multidex = "2.0.1"
okhttp = "4.12.0"
recyclerview = "1.3.2"
localbroadcastmanager = "1.1.0"
documentfile = "1.0.1"
material = "1.12.0"
startupRuntime = "1.1.1"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
localbroadcastmanager = { group = "androidx.localbroadcastmanager", name = "localbroadcastmanager", version.ref = "localbroadcastmanager"}
documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
material   = { group = "com.google.android.material", name = "material", version.ref = "material" }
startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

